// 'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

// import { createContext } from 'react';

const inter = Inter({ subsets: ['latin'] });

// type Theme = {
//   colors: {
//     primary: string;
//     secondary: string;
//   };
// };

// const defaultTheme: Theme = {
//   colors: {
//     primary: '#007bff',
//     secondary: '#6c757d',
//   },
// };

// const ThemeContext = createContext<Theme>(defaultTheme);

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ThemeProvider>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
